---
title: "7331 Lab 3"
author: "Krithika Kondakindi, Christopher Williams, Jason Yoon"
date: "2023-08-08"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(arules)
library(arulesViz)
```

```{r}
drivers = read_csv("https://raw.githubusercontent.com/the-mcw/ML1/main/data/drivers_6.csv")
```

```{r}
rm_drivers = drivers %>%
  select(c(1,4,5,12,18,19,24,30,9)) %>%
  arrange(raceId) %>%
  group_by(driverId, year) %>%
  mutate(nextFinish = lead(positionOrder)) %>%
  ungroup() %>%
  select(-c(positionOrder,year))

rm_drivers = rm_drivers %>%
  rename(nextQualify = qualifyPosition) %>%
  mutate(points_Race = pointsSeason/round,
         conPoints_Race = ConstructorSeasonPoints/round) %>%
  select(-c(pointsSeason,ConstructorSeasonPoints)) %>%
  relocate(starts_with("next"), .after = last_col())

rm_drivers = rm_drivers %>%
  mutate(pointsBin = cut(points_Race, c(0,1,15,26),
                       labels = c("no points", "midfield", "podium"),
                       include.lowest = T, right = F),
         conBin = cut(conPoints_Race, c(0,1,15,44),
                      labels = c("no points", "midfield", "podium"),
                      include.lowest = T, right = F),
         rankBin = if_else(rank==0,"no points",
                           cut(rank, 4, labels = c("Q1", "Q2","Q3", "Q4"),
                               #c(1,3,10,24), labels = c("podium", "midfield", "no points"),
                               include.lowest = T)),
         nextQualBin = cut(nextQualify,c(1,4,8,14,24), labels = c("1-4", "5-8", "9-14","back"),
                        include.lowest = T),
         nextFinBin = cut(nextFinish, c(1,3,10,24), labels = c("podium", "midfield", "no points"),
                          include.lowest = T))

rm_model_drivers = rm_drivers %>%
  select(ends_with("Bin")) %>%
  mutate(rankBin = factor(rankBin))
```

## Podium Finishes
Find Associations
```{r, results='hide'}
rm_podium = apriori(rm_model_drivers,
                   parameter = list(support = 0.05, confidence = 0.5, minlen = 2),
                   appearance = list(rhs = c("nextFinBin=podium")))
```
```{r}
knitr::kable(DATAFRAME(rm_podium,
                       setStart = "",
                       itemSep = " | ",
                       setEnd = ""),
             "pipe")
```


## Non-Podium Point Finishes
```{r, results='hide'}
rm_midfield = apriori(rm_model_drivers,
                   parameter = list(support = 0.075, confidence = 0.4, minlen = 2),
                   appearance = list(rhs = c("nextFinBin=midfield")))
```
```{r}
knitr::kable(DATAFRAME(rm_midfield,
                       setStart = "",
                       itemSep = " | ",
                       setEnd = ""),
             "pipe")
```



